version: '3'

services:

  web:
    image: app-mongodb
    container_name: app-mongodb
    build: .
    command: "node server.js"
    ports:
      - "5000:5000"
    restart: unless-stopped  
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo   
    ports:
      - "27017:27017"
    restart: unless-stopped     
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express   
    ports:
      - 8081:8081
    restart: unless-stopped   

